spring:
  data:
    mongodb:
      host: 192.168.10.91
      port: 10000
      database: sdnDB
#      database: weidd
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=2,expireAfterAccess=1800s
    cache-names: analyses, original
  jpa:
    show-sql: true
logging:
  level:
    root: info
    org.spark_project.jetty: info
    org.springframework.data.mongodb.core: debug
    org.springframework.data.mongodb.repository: debug
    com.butel.project: debug
  file: D:\logs\relay_proxy.log
  pattern:
#    file: "%msg%n"
    console: "%msg%n"
server:
  port: 8090
  servlet:
    context-path: /
debug: false