spring:
  data:
    mongodb:
      host: 192.168.10.91
      port: 10000
      database: sdnDB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=2,expireAfterAccess=1800s
    cache-names: analyses
logging:
  level:
    com.butel.project: debug
  file: D:\logs\relay_proxy.log
server:
  port: 8090
  servlet:
    context-path: /
debug: false